### ISSUE TITLE
how do i get the specific emotion( the maximum value in the list of emotions)

### ISSUE THREAD

**Issue by Philip-Leron** [justinshenk/fer#3]

**Comment by justinshenk** [comment]
Hi @Philip-Leron, try version 19.0.0. I added `detector.top_emotion(img)`, which outputs `emotion, score` of the first face found in the image.

**Comment by Philip-Leron** [comment]
Thanks Justin

**Comment by Gauravajariwal11** [comment]
Hi, 

I am using this to extract emotions from a video file. I also need the top emotion, but I think your method top_emotion takes an image's input. Any suggestions how I should tackle this? I am using pretty much same code as yours from video-example.py

**Comment by justinshenk** [comment]
Hi Gaurav,
That functionality can be added to the Video class by reusing some code
from top_emotion. Feel free to make a pull request.

**Comment by Gauravajariwal11** [comment]
hi @justinshenk , thanks. I will do that. Also, there is one issue that I am facing. Not sure if you have faced or not, but sometimes i think the model fails to capture all the frames? For the video that I am processing, the frames should be 3000+ but I end up getting only 1500. Do you happen to know something about why that happens? Thanks in advance.

**Comment by Gauravajariwal11** [comment]
@justinshenk I need to look up, but what I have noticed is that for your test.mp4 video, there should be 115 frames, which means 115 rows of 7 emotions, but the data.csv files output only 90. For my videos, the total frames are 3000, but the data.csv shows 1500. So it is probably either skipping frames, or the data writer function is not writing things correctly.

**Comment by justinshenk** [comment]
I am looking at the code for the first time in a while, and I see a
capture_duration variable set to 1000 / fps. This is about 30 seconds for
30 fps. I can't answer the question why this is there right now since it is
not documented, but is your video longer? I would first see if it is
finishing early because of this mystery variable.

**Comment by Gauravajariwal11** [comment]
@justinshenk  Sorry for disturbing you. I am not sure myself why this is happening. The most plausible explanation that I have is that the model failed to capture the face or franes. Because I just tried running on another similar video. Out of 3444 frames, 3400 were saved/captured/recognized. 

As compared to previous video in which only 1500 were captured out of 3000. Also both the videos are approximately 110 seconds long.

**Comment by vichidamba** [comment]
Is this error solved?

**Comment by Philip-Leron** [comment]
Yeah. İt was helpful during my final exam

**Comment by vichidamba** [comment]
No, I am also getting a mismatch in the output frame count from data.csv. It seems the model is skipping predictions when a face is to detected in a frame instead of outputting zero at that frame. Any solution for this?

**Comment by Philip-Leron** [comment]
İ will have a look at that project again it is been long since i checked it
out
